### ISSUE TITLE
Question about delete-to-end of line

### ISSUE THREAD

**Issue by satyagraha** [alphabotsec/vscode-eclipse-keybindings#10]
Hi, can the above be supported? It's usually mapped to ctl-shift-del. I haven't seen a definitive list of the available editor actions so not sure whether feasible or not.
Thanks for the good work anyway 👍

**Comment by p-** [comment]
Hi, I mapped ctrl+shift+delete to the command with the nice name `deleteAllRight`.
Released with 0.9.6.
You're welcome!

**Comment by satyagraha** [comment]
Many thanks, works perfectly :-)
