### ISSUE TITLE
How to disable some keybindings

### ISSUE THREAD

**Issue by Ltre** [alphabotsec/vscode-eclipse-keybindings#11]
For example, the keybinding [CTRL+K] affects the original shortcut key function of VSCODE.
Thanks!

**Comment by p-** [comment]
Hi!
You can remove a keybinding for an action as described in the [VS Code doc](https://code.visualstudio.com/docs/getstarted/keybindings#_removing-a-specific-key-binding-rule).
So in that case like this:
```
    {
        "key": "ctrl+k",
        "command": "-editor.action.nextSelectionMatchFindAction",
        "when": "editorTextFocus"
    }
```
