### ISSUE TITLE
key binding not working completely after update vo vs 2.4.1

### ISSUE THREAD

**Issue by dailin1979** [alphabotsec/vscode-eclipse-keybindings#14]
Hi,

after update my vs code to newst version, i find out some of key bindings do not work any more, such als 

             {
                "mac": "cmd+alt+t",
                "win": "ctrl+alt+t",
                "linux": "ctrl+alt+t",
                "key": "ctrl+alt+t",
                "command": "workbench.action.terminal.toggleTerminal"
            },
            {
                "mac": "cmd+shift+delete",
                "win": "ctrl+shift+delete",
                "linux": "ctrl+shift+delete",
                "key": "ctrl+shift+delete",
                "command": "deleteAllRight",
                "when": "editorTextFocus"
            },

does someone else have also this problem?

**Comment by p-** [comment]
Hi!
We do not have those issues. Are you still having those problems?
Which exact version of VS Code and which operating system are you using?

**Comment by p-** [comment]
No answer -> closing.
Please reopen if the problem still exists.
