### ISSUE TITLE
New keybinding for VS Code 1.25.1

### ISSUE THREAD

**Issue by saravanavela** [alphabotsec/vscode-eclipse-keybindings#15]
Please add key binding for new features added in VS Code 1.25.1 like cursorWordPartRight etc..

**Comment by p-** [comment]
Good idea!
If possible could you please provide a list of all subword keybindings which should be supported and to which key combination they should map to?

E.g. `cursorWordPartRight` should map to `ctrl+right`

**Comment by p-** [comment]
Sub-word navigation and selection has been added in 0.10.0.
