### ISSUE TITLE
Suggestion : Use code action kinds to provide "export to method" and "export to variable"

### ISSUE THREAD

**Issue by dlicois** [alphabotsec/vscode-eclipse-keybindings#18]
Hello,

According to https://code.visualstudio.com/docs/editor/refactoring#_keybindings-for-code-actions, it should be possible to reproduce Eclipse's direct keybind for "extract to local variable" and "extract method" instead of going through the quickfix keybind.

The code action kinds contributions are missing as of now, but I reached out to vscode-java extension devs and it should be done for the next milestone.
redhat-developer/vscode-java#714

Once the code action kinds contributions are done, it should be trivial to add the missing keybinds

```
{
    "mac": "cmd+shift+l",
    "win": "alt+shift+l",
    "linux": "alt+shift+l",
    "key": "alt+shift+l",
    "command": "editor.action.codeAction",
    "args": {
        "kind": "refactor.extract.variable",
        "apply": "ifSingle"
    }
    "when": "editorTextFocus"
},
{
    "mac": "cmd+shift+m",
    "win": "alt+shift+m",
    "linux": "alt+shift+m",
    "key": "alt+shift+m",
    "command": "editor.action.codeAction",
    "args": {
        "kind": "refactor.extract.function",
        "apply": "ifSingle"
    }
    "when": "editorTextFocus"
}
```

(kind strings might be different, waiting on vscode-java)

**Comment by p-** [comment]
Hey @dlicois 
Sounds great!

If possible: could you update this issue or even create a pull request when vscode-java is ready?

Thanks!

**Comment by dlicois** [comment]
Yes I'm following closely the issue in vscode-java. I'll see if I can find time to make it work when the support lands in vscode-java master. So that we may have a release ready on day 0.

**Comment by dlicois** [comment]
redhat-developer/vscode-java#714 is closed and the 0.36 version of vscode-java is on the marketplace.

I don't have a PR yet though.

**Comment by p-** [comment]
@dlicois any updates on this? ;)

**Comment by p-** [comment]
Key bindings for "extract method" and "extract local variable" were added with following pull requests:
https://github.com/alphabotsec/vscode-eclipse-keybindings/pull/45
https://github.com/alphabotsec/vscode-eclipse-keybindings/pull/46

Please reopen this issue if they do not work as intended.
