### ISSUE TITLE
It does not look like workbench.action.splitEditor gets registered

### ISSUE THREAD

**Issue by JPinkney** [alphabotsec/vscode-eclipse-keybindings#23]
Hi,

It does not look like the workbench.action.splitEditor keybinding ['ctrl+{'](https://github.com/alphabotsec/vscode-eclipse-keybindings/blob/master/package.json#L94) gets registered in VSCode. Just from some preliminary observations it looks like VSCode does not support '{' in the accepted keys for keybindings: https://code.visualstudio.com/docs/getstarted/keybindings#_accepted-keys.

If that is the case, I'm not sure if it would be better to change the keybinding or remove it from the package.json (since people would not have been able to use it anyways so it would not break anyones workflow)

WDYT?

**Comment by p-** [comment]
Hi @JPinkney 
Thanks for bringing this up!
Yeah, I think we should remove it then.

So we just use `ctrl+2` as defined from VS Code.

**Comment by JPinkney** [comment]
I've created a PR: https://github.com/alphabotsec/vscode-eclipse-keybindings/pull/24

**Comment by p-** [comment]
Thanks!
