### ISSUE TITLE
Map ctrl+f to editor.action.startFindReplaceAction

### ISSUE THREAD

**Issue by jeffjensen** [alphabotsec/vscode-eclipse-keybindings#27]
VC default maps ctrl+f to actions.find.  Eclipse's ctrl+f opens the find/replace dialog.

Additionally, since this extension maps ctrl+h to workbench.view.search, this change maps a convenient way to open find/replace.

**Comment by p-** [comment]
Hi Jeff,
I'm not sure on this one. As it is easily possible to switch from the Find dialog to the Replace dialog by clicking the arrow to the left of the Find-dialog.

**Comment by jeffjensen** [comment]
Yes, requires using the mouse (usability hit) or to stay on keyboard "Shift+Tab, Space, Tab" then typing criteria; neither are convenient.

Prior I looked into changing the mapping but I did not see how to open the VS Code Find dialog with the Replace section open, so I don't know if this is even possible.

**Comment by mrx23dot** [comment]
Yeah I noticed this too, VS code likes to use icons and drop downs to make life harder.

**Comment by p-** [comment]
Ok, let's do this!

**Comment by mozhuanzuojing** [comment]
This fix will make it impossible to use Ctrl+F to find when opening a class file

**Comment by p-** [comment]
@mozhuanzuojing 

>This fix will make it impossible to use Ctrl+F to find when opening a class file

Could you please expand on what you mean by that?
it seems to be possible use Ctrl+F or Cmd+F when opening a .java or a .class file. Instead of the search box the "search and replace" box opens. But it's possible to search with the "search and replace" box. (Like in Eclipse)
Or do you mean something else?

**Comment by mozhuanzuojing** [comment]
@p- 

> success op in *.java

![image](https://user-images.githubusercontent.com/63572041/169723318-0978d6c0-ce49-4ecb-93f0-001f12aff2ad.png)


> fail op in *.class

![image](https://user-images.githubusercontent.com/63572041/169723404-20e3b6d7-e26b-4394-86be-b0b14be466d5.png)

**Comment by p-** [comment]
@mozhuanzuojing 

Thanks for your feedback. Yes, I think we'll have to remove that keybinding again until we have found a better solution (if there is one).
