### ISSUE TITLE
VSCodium does not find eclipse keymap on marketplace

### ISSUE THREAD

**Issue by de-jcup** [alphabotsec/vscode-eclipse-keybindings#33]
When trying to install keymap on VSCodium 1.47.1 via <kbd>CTRL</kbd> + <kbd>P</kbd> and entering `ext install alphabotsec.vscode-eclipse-keybindings` as described on
https://marketplace.visualstudio.com/items?itemName=alphabotsec.vscode-eclipse-keybindings

the keymap is not listed:
![image](https://user-images.githubusercontent.com/11644753/87779435-10d99580-c82d-11ea-96a3-9501c9c5fd9f.png)

**Comment by p-** [comment]
Hello!
I think VSCodium uses [Open VSX](https://open-vsx.org) as a marketplace and not the one from Microsoft. I published the extension on Open VSX as well. Could you please check if you are able to install the extension?

**Comment by de-jcup** [comment]
Hello @p- ,

just tried out - is now listed in VSCodium and works well!

Thank you very much !
