### ISSUE TITLE
Feature request: CTRL + F7 (switch focus between windows)

### ISSUE THREAD

**Issue by radoslav006** [alphabotsec/vscode-eclipse-keybindings#36]
I am missing the eclipse ctrl+f7 shortcut to switch focus between windows (explorer, editor, terminal). Unfortunately I don't know if there is option to implement it and how to add it by myself, hope someone consider it helpful and add it.

**Comment by p-** [comment]
Hi @radoslav006 
Could it be something like the current `F6` in VS Code?
That would be `workbench.action.focusNextPart`.

Cheers

**Comment by radoslav006** [comment]
Hi p-! Thanks for your response. Yes, indeed, it's something like that! Is there option to go back as well (e.g. `workbench.action.focusPreviousPart`)?
In eclipse, after ctrl+f7 there appears a nice mini-list and you can select the element that you want to jump to, but I think if there will be option to go forth and back it may be sufficient.

**Comment by p-** [comment]
Released with 0.13.0. Enjoy!
