### ISSUE TITLE
add keybindings for features from vscode-java

### ISSUE THREAD

**Issue by CsCherrYY** [alphabotsec/vscode-eclipse-keybindings#42]
Currently, [vscode-java](https://github.com/redhat-developer/vscode-java) has supported a lot of Java features, some of them like `Show Type Hierarchy` and other refactoring actions like `Extract Method` and `Extract Variable` don't have proper keybindings yet. It would be great if we can add eclipse keybindings for these features.

**Comment by CsCherrYY** [comment]
I have created #43, #44, #45 and #46 to support this. @p- could you take a look?

**Comment by p-** [comment]
Hi @CsCherrYY Thank you very much for your additions!
I will test them as soon as possible.

**Comment by p-** [comment]
Thanks again. All your submissions have just been released.
