### ISSUE TITLE
Can you please include ctrl+k and ctrl+shift+k shortcuts ?

### ISSUE THREAD

**Issue by weaseliam** [alphabotsec/vscode-eclipse-keybindings#5]
These shortcuts are used for quick searching current editor selection.
`
    { "key": "ctrl+k",       "command": "editor.action.nextSelectionMatchFindAction",
                             "when": "editorFocus" },
    { "key": "ctrl+shift+k", "command": "editor.action.previousSelectionMatchFindAction",
                             "when": "editorFocus" }
`

**Comment by p-** [comment]
Thanks! published with 0.9.3

**Comment by Ltre** [comment]
How to disable the [CTRL+K] keybinding?
I wanna to disable only one.
It affects the original shortcut key function of VSCODE.
Thanks!
