### ISSUE TITLE
F5 (start debug) shows extra popup window

### ISSUE THREAD

**Issue by mrx23dot** [alphabotsec/vscode-eclipse-keybindings#50]
Using with Python3 I press F5 to start debugging then it shows this annoying pop up everytime: (from I always go with first one)

![pop](https://user-images.githubusercontent.com/4163396/152385944-b8742f79-cfba-4aa3-a46b-badd82f211e3.jpg)

but when I select it here it starts debugging instantly without popup:
![good](https://user-images.githubusercontent.com/4163396/152386018-359bbec9-a8ea-4833-ad72-e7abf58d6ae2.jpg)
![start](https://user-images.githubusercontent.com/4163396/152386322-81de8652-9237-4e2f-b338-1664ffd293fc.jpg)

So I think it's mapped to something different.

**Comment by p-** [comment]
Hi @mrx23dot 
I'm not sure if I understand your issue correctly.
`F5` is mapped to to Step Into. (while debugging)
Start debugging would be: `Ctrl+f11` (On Windows and Linux)

**Comment by mrx23dot** [comment]
Yeah you are right, although it should be simple F11:
![2022-03-11 09_48_10-C_C++ - gen3_main c - Eclipse](https://user-images.githubusercontent.com/4163396/157843221-d16ea18b-d339-4ab9-a95a-0b407baede7e.jpg)

But CTRL+F11 still displays the **select configuration drop down** which really annoying.
Not sure why is it happening:
![2022-03-11 09_53_05-Keyboard Shortcuts  Administrator](https://user-images.githubusercontent.com/4163396/157844059-f5db7727-3f3c-43d3-bd31-d20b62ca60c2.jpg)

and it doesn't happen if I press the` debug button` instead. (see original post)

Does this happen for you too? Maybe it only happens with python.

**Comment by mrx23dot** [comment]
Solved it,  launch.json has to be created that contains debug config, or F11 can be mapped to "python.debugInTerminal" although it's python extension specific.
