### ISSUE TITLE
Is there a way to import an Eclipse C project into Visual Studio Code

### ISSUE THREAD

**Issue by sajeevank** [alphabotsec/vscode-eclipse-keybindings#58]
Hi,
When search in google for "Importing Eclipse C project into Visual Studio Code", it immediately gives a link: https://docs.wpilib.org/en/2020/docs/software/wpilib-overview/importing-eclipse-project.html
But this is not working. As per their latest web page 2022, WPILib not supporting this: https://docs.wpilib.org/en/2022/docs/software/vscode-overview/index.html.
What is shown in this page is only eclipse keybindings-not an eclipse extension for Visual Studio code.
When I import an Eclipse C project with the Command: Torizon C/C++ Import existing Application, It is showing the error message: No Templates found.
So how can I do this ?
Thanks in advance for the help.
Sajeevan

**Comment by p-** [comment]
Hi @sajeevank 

Yes, this extension here exists that users can use the keybindings of Eclipse with Visual Studio Code. It does not provide any other features (Especially no C/C++ features 😉 ).
I think you have to look for another extension.

Sorry if I haven't understood your question correctly.

**Comment by p-** [comment]
Hi @sajeevank 
I'm closing this issue. Thanks
(You can still open a new issue if its related to these keybindings here.)
