### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by CsCherrYY** [alphabotsec/vscode-eclipse-keybindings#59]
@p- since a lot of changes (#41, #43, #44, #45, #46, #52, #54, #55, #56) have been merged, can we release a new version so the users can benefit from them?

**Comment by p-** [comment]
Hi @CsCherrYY 

Thanks for asking. I was planning to create a new release this month (May). I want to test the newly submitted changes once more.
As a matter of fact #41, #43, #44, #45 and #46 have already been released last year (July 4, 2021) with the [0.14.0 release](https://github.com/alphabotsec/vscode-eclipse-keybindings/blob/master/CHANGELOG.md#0140-july-4-2021).

Thanks again for your changes, I will inform you via this issue once the release is done.

**Comment by CsCherrYY** [comment]
Sorry for my mistake on the changes, you're right. And thanks for the reply.

And BTW do you have any plan (or time) on reviewing and merging PR, and publishing a new version of this project in the long term? I'm willing to help you on this since our team (VS Code Java team) would like this extension to keep updated with new features in VS Code which has related default keybindings in Eclipse.

If so, I'm happy to bring some news. And if not, could you add me as the collaborator of this repo so I can make efficient changes?

**Comment by p-** [comment]
>And if not, could you add me as the collaborator of this repo so I can make efficient changes?

Hi @CsCherrYY, Your help is appreciated!
I sent you an email, please respond there.

**Comment by p-** [comment]
Hi @CsCherrYY 
Version 0.16.0 has just been released and should be available on the [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=alphabotsec.vscode-eclipse-keybindings) and [Open VSX](https://open-vsx.org/extension/alphabotsec/vscode-eclipse-keybindings) within minutes.

Thanks for your help!
