### ISSUE TITLE
Do not active Replace mode when press ctrl+f to call Find

### ISSUE THREAD

**Issue by ghost** [alphabotsec/vscode-eclipse-keybindings#60]
keep it as it is！！！
I always press Enter to search next one after press ctrl+f.
now,this action will replace my keyword to nothing.
do some human affairs！！！
press CTRL+F,
Replace will active and replace's input be focus,
press Enter,
replace first matched to nothing and goto next match.
Replace mode is not activated until update to new version.
This update has caused users to change their operating habits.

**Comment by p-** [comment]
Hi @saatana97 

This keybinding was introduced in the hope that the behavior would be similar to the Eclipse one.
https://github.com/alphabotsec/vscode-eclipse-keybindings/issues/27

But we'll remove the keybinding again.

**Comment by ghost** [comment]
now,if I want search something,
double click to selected some text,
press CTRL+F,
mouse click arrow icon to close Replace mode,
then press Enter jump to matched.
I think use Find times more than use Replace times,
this update sacrifices the convenience of shortcut keys.
or only Find has any special shortcut keys?

Thank you for your contributions to the developers.

**Comment by p-** [comment]
Change was reverted in the just released version 0.16.1.
