### ISSUE TITLE
Mac OS X default behavior for [ALT] + [<-] and [ALT] + [->] overriden

### ISSUE THREAD

**Issue by ThFischer** [alphabotsec/vscode-eclipse-keybindings#8]
Version 0.9.3
In MacOS / OS X the default behaviour for ⌥ → (next word) and ⌥ ← (previous word) are now overridden with workbench.action.navigateForward and navigateBack

**Comment by p-** [comment]
Hi. Thanks for reporting!
Released with 0.9.5
